"""empty message

Revision ID: feba88a5288f
Revises: e8255125dea3
Create Date: 2026-08-24 12:34:38.763199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feba88a5288f'
down_revision: Union[str, Sequence[str], None] = 'e8255125dea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_content_tsv'), table_name='chunk', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chunk_content_tsv'), 'chunk', ['content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
